SET IDENTITY_INSERT [dbo].[Sports] ON
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (149, N'Archery')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (150, N'Rugby')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (151, N'Wrestling')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (152, N'High jumping')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (153, N'Hang gliding')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (154, N'Car racing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (155, N'Cycling')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (156, N'Running')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (157, N'Table tennis')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (158, N'Fishing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (159, N'Judo')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (160, N'Climbing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (161, N'Billiards/ Pool (U.S.)')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (162, N'Shooting')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (163, N'Horse racing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (164, N'Horseback riding')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (165, N'Baseball')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (166, N'Golf')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (167, N'Basketball')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (168, N'Volleyball')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (169, N'Badminton')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (170, N'Cricket')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (171, N'Bowling')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (172, N'Boxing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (173, N'Curling')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (174, N'Tennis')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (175, N'Skateboarding')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (176, N'Surfing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (177, N'Hockey')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (178, N'Figure skating')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (179, N'Yoga')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (180, N'Fencing')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (181, N'Fitness')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (182, N'Gymnastics')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (183, N'Karate')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (184, N'Weightlifting')
INSERT INTO [dbo].[Sports] ([SportId], [Name]) VALUES (185, N'Football')
SET IDENTITY_INSERT [dbo].[Sports] OFF
